### ISSUE TITLE
没解决no data

### ISSUE THREAD

**Issue by chenyuyou** [koolob/rrshare#1]
我试了下，感觉还是no data

**Comment by koolob** [comment]
> 我试了下，感觉还是no data

已经更新了一个修复版本。可以重新build一下。启动脚本也有更改。

**Comment by jianhuiz** [comment]
原来的方法好用，就是需要清浏览器缓存，才会下载新的js文件

**Comment by koolob** [comment]
> 原来的方法好用，就是需要清浏览器缓存，才会下载新的js文件

嗯，就是比较麻烦。新方法直接可用，方便一些。
